# Generated by Django 3.1.3 on 2021-04-28 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audiobook',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('author', models.TextField(max_length=100)),
                ('narrator', models.TextField(max_length=100)),
                ('duration', models.DurationField()),
                ('upload_time', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Podcast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('duration', models.DurationField()),
                ('upload_time', models.DateTimeField(auto_now=True)),
                ('host', models.TextField(max_length=100)),
                ('participants', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('duration', models.DurationField()),
                ('upload_time', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
